heat_template_version: 2014-10-16

parameters:
  Flavor:
    description: Flavor of the datanode server
    type: string
    default: m1.xlarge
  KeyName:
    description: Name of an existing ssh keypair
    type: string
  PrivateNet:
    description: Private network for pnda deployment
    type: string
  PrivateSubnet:
    description: Private network for pnda deployment
    type: string
  Image:
    type: string
  name:
    type: string
  SaltmasterIP:
    type: string
  NodeIndex:
    type: number
    default: 0
  sec_group:
    type: string
  volume_size:
    type: number
    default: 200
  mountpoint:
    type: string
    default: /dev/vdc
  cluster_name:
    type: string
  pnda_secgroup:
    type: string
  pnda_flavor:
    type: string
    default: default
  logvolume_size:
    type: number
    default: 250
  log_mountpoint:
    type: string
    default: /dev/vdb


resources:
  port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: PrivateNet }
      fixed_ips:
        - subnet_id: { get_param: PrivateSubnet }
      security_groups: [{ get_param: sec_group }]
  install_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        str_replace:
          template: {get_file: scripts/base_install.sh }
          params:
            $flavor$: { get_param: pnda_flavor }
            $master_ip$: { get_param: SaltmasterIP }
            $pnda_cluster$: { get_param: cluster_name }
            $volume_dev$: { get_param: log_mountpoint }
            $roles$: 'cloudera_datanode'
            $cloudera_role$: 'DATANODE'
            $brokerid$: ''
  install_deployment:
    type: OS::Heat::SoftwareDeployment
    depends_on: [ volume_attachment, logvolume_attachment ]
    properties:
      signal_transport: TEMP_URL_SIGNAL
      config:
        get_resource: install_config
      server:
        get_resource: server

  server:
    type: OS::Nova::Server
    properties:
      name: { get_param: name }
      image: { get_param: Image }
      flavor: { get_param: Flavor }
      key_name: { get_param: KeyName }
      networks: [{ network: {get_param: PrivateNet}}]
      security_groups: [{ get_param: sec_group }, { get_param: pnda_secgroup }]
      software_config_transport: POLL_TEMP_URL
      user_data_format: SOFTWARE_CONFIG
      config_drive: True

  volume:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: volume_size }
      description: Volume for datanode
  volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: volume }
      instance_uuid: { get_resource: server }
      mountpoint: { get_param: mountpoint }
  logvolume:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: logvolume_size }
      description: Volume for datanode logs
  logvolume_attachment:
    type: OS::Cinder::VolumeAttachment
    depends_on: volume_attachment
    properties:
      volume_id: { get_resource: logvolume }
      instance_uuid: { get_resource: server }
      mountpoint: { get_param: log_mountpoint }


outputs:
  port_resource:
    description: Heat resource handle for the Neutron port
    value:
      { get_resource: port }
  server_resource:
    description: Heat resource handle for the Nova compute server
    value:
      {get_resource: server}
  hosts_entry:
    description: >
      Server's IP address and hostname in the /etc/hosts format
    value:
      str_replace:
        template: |
          PRIMARYIP PRIMARYHOST
        params:
          PRIMARYIP: {get_attr: [server, first_address]}
          PRIMARYHOST: {get_attr: [server, name]}
